[build]
  base    = "portfolio"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.3"

[[redirects]]
  from = "/api/*"
  to   = "https://amitpatil-ai-backend.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
